### PR TITLE
Add methods to set the SSH identity

### LINKED ISSUE #10: Add option to set private key or private key file
~~Maybe `$repo->setSshKey()` and `$repo->setSshKeyFile()` ?~~

`setSshIdentity(string $privateKey): static`
`setSshIdentityPath(string $privateKeyPath): static`

### PR DESCRIPTION
**Pull request by ausi**
First draft for #10

Method is a bit different because we have to handle the known_hosts too I think. 
/cc @Toflar

### CODE REVIEW

**Comment by Toflar** [comment]
Looks good, just wondering if we should also lock 🤔 Otherwise multiple processes might potentially access the same file and suddenly use the wrong key. Not sure if possible but I don't think `gitDir` is random enough?

**Comment by ausi** [comment]
> but I don't think `gitDir` is random enough?

It uses Symfonys `Filesystem::tempnam()` so uniquness should be guaranteed. And even if not, a second `git init` call to the same directory would fail.

**Comment by Toflar** [comment]
LGTM then!

**Comment by ausi** [comment]
CI needs to be fixed. Apart from that, this is RTM IMO.

**Review by Toflar — APPROVED** [review]

**Pull request merged**
